apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-of-apps
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Junho-06/argocd-sample-app.git
    path: getting-started/argocd
