server:
  rbacConfig:
    # samples: https://github.com/argoproj/argo-cd/blob/master/assets/builtin-policy.csv
    # p, role:readonly, exec, get, */*, allow
    policy.csv: |
      g, khu-dev:khumu-developer, role:readonly
      g, khu-dev:khumu-devops, role:admin
