apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jinsu-team-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/umi0410/declarative-argocd.git
    targetRevision: HEAD
    path: getting-started/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jinsu-team-front
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/umi0410/declarative-argocd.git
    targetRevision: HEAD
    path: getting-started/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: other-team-data
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/umi0410/declarative-argocd.git
    targetRevision: HEAD
    path: getting-started/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/umi0410/declarative-argocd.git
    targetRevision: HEAD
    path: getting-started/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/umi0410/declarative-argocd.git
    targetRevision: HEAD
    path: getting-started/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/umi0410/declarative-argocd.git
    targetRevision: HEAD
    path: getting-started/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true